In [1]:
import numpy as np
import trimesh

SVG path loading unavailable!
Traceback (most recent call last):
  File "/home/prak/anaconda/envs/lidar/lib/python3.7/site-packages/trimesh/path/exchange/svg_io.py", line 18, in <module>
    from svg.path import parse_path
ModuleNotFoundError: No module named 'svg'


In [2]:
msh = trimesh.load_mesh("mesh.ply")

In [3]:
msh.show()

/home/prak/anaconda/envs/lidar/lib/python3.7/site-packages/IPython/core/display.py:689: UserWarning: Consider using IPython.display.IFrame instead
  warnings.warn("Consider using IPython.display.IFrame instead")


In [4]:
with open("sfm.csv") as f:
    pts = np.asarray([[float(e) for e in row.split(",")] for row in f.readlines()])[:,:3]

In [6]:
trimesh.registration.icp(pts, msh, reflection=False)

(array([[ 6.93888896e-01, -1.42309124e-02, -5.03253303e-02,
          1.87069569e+05],
        [ 2.65392311e-02,  6.72793866e-01,  1.75673108e-01,
          1.38448912e+06],
        [ 4.50646974e-02, -1.77095604e-01,  6.71433748e-01,
          7.37594697e+05],
        [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
          1.00000000e+00]]),
 array([[4.12445397e+05, 4.26586173e+06, 2.17235149e+03],
        [4.12446342e+05, 4.26586196e+06, 2.17236467e+03],
        [4.12446515e+05, 4.26586280e+06, 2.17213505e+03],
        ...,
        [4.12445536e+05, 4.26586275e+06, 2.17284021e+03],
        [4.12441203e+05, 4.26586261e+06, 2.17224593e+03],
        [4.12443011e+05, 4.26586287e+06, 2.17242462e+03]]),
 0.1274317492690615)

In [7]:
trimesh.registration.icp?

Signature:
trimesh.registration.icp(
    a,
    b,
    initial=array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]]),
    threshold=1e-05,
    max_iterations=20,
    **kwargs,
)
Docstring:
Apply the iterative closest point algorithm to align a point cloud with
another point cloud or mesh. Will only produce reasonable results if the
initial transformation is roughly correct. Initial transformation can be
found by applying Procrustes' analysis to a suitable set of landmark
points (often picked manually).

Parameters
----------
a : (n,3) float
  List of points in space.
b : (m,3) float or Trimesh
  List of points in space or mesh.
initial : (4,4) float
  Initial transformation.
threshold : float
  Stop when change in cost is less than threshold
max_iterations : int
  Maximum number of iterations
kwargs : dict
  Args to pass to procrustes

Returns
----------
matrix : (4,4) float
  The transformation matrix sending a to b
transformed : (n,3) fl

In [8]:
_[0]

array([[ 6.93888896e-01, -1.42309124e-02, -5.03253303e-02,
         1.87069569e+05],
       [ 2.65392311e-02,  6.72793866e-01,  1.75673108e-01,
         1.38448912e+06],
       [ 4.50646974e-02, -1.77095604e-01,  6.71433748e-01,
         7.37594697e+05],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         1.00000000e+00]])

In [11]:
print(tfm)

[[ 6.93888896e-01 -1.42309124e-02 -5.03253303e-02  1.87069569e+05]
 [ 2.65392311e-02  6.72793866e-01  1.75673108e-01  1.38448912e+06]
 [ 4.50646974e-02 -1.77095604e-01  6.71433748e-01  7.37594697e+05]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
